LinearSearchAlgoritm_C++.cpp

I have added Implementation of Linear Search Algorithm in C++ Language.

Added Implementation of Linear Search Algorithm in C++

---

Linear-Search-Algorithm_in_c++.cpp

Create LinearSearchAlgorithm in C++.
Algorithm is well explained using comments.

Linear-Search-Algorith-Done_using_c++

---

Bellman_Ford_Algorithm_CPP.cpp

Added Bellman Ford Algorithm in CPP

---

BubbleSort.C++
CoinChangeProblem.C++

Explained Bubble Sort with Proper comments

Bubble sort

---

CoinChangeProblem.C++

Completed Coin Change Problem with two approaches Properly explained with comments.

Added Coin Change Problem

---

HeapSortAlgorithm_C++.cpp

Uploaded code with explanation for Heap Sort Algorithm implemented in C++

Heap Sort Algorithm - C++

---

BubbleSort_Java.java
InsertionSort_Java.java
SelectionSort_Java.java

Bubble Sort and Insertion Sort in Java

---

MergeSort_Java.java

Merge sort Java added

---

QuickSort_Java.java

QuickSort Java added

---

Euclids-algorthm_C++.cpp

Euclid's algorithm implemented

---

InsertionSort_Python.py

Insertion Sort Python added

---

BogoSort.c
insertion sort java

created code for insertion sort in c++

Create insertion sort c++

---

regressionmodel.py

Please review and merge my linear regression model under hacktoberfest2022

Add linear regression model

---

BFS algorithm
depth first search algorithm
selection sort C++

created code for selection sort algorithm

Create selection sort C++

---

Depth_First_Search_(DFS)_Algorithm.cpp

1)Defination of Depth First Search (DFS) Algorithm
2) Time Complexity analysis 
3) code

Added code of Depth First Search (DFS) Algorithm

---

Coin Change Problem (PYTHON))

Coin Change Problem (PYTHON))

---

Quick sort (PYTHON)

Python program for implementation of Quicksort Sort

Quicksort Sort(PYTHON)

---

BFS(PYTHON)

BFS(PYTHON)

---

FloydWarshallAlgorithm.cpp

Added FloydWarshallALgorithm.cpp to find shortest path

---

DiceRoll.py
MontyHall.py

I added the all-time favorite Monty Hall problem and a classic Dice Roll problem.
Monty Hall Problem and Dice Roll Problem are two problems that I have added; the description of these problems is written in the codes themselves.

Added two interesting problems in python language
